name: mltest
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  camera: ^0.11.0+1
  path_provider: ^2.1.3
  path: ^1.9.0
  google_mlkit_text_recognition: ^0.13.0
  provider: ^6.1.2
  image_field: ^0.0.10
  image_picker: ^1.1.2
  logger: ^2.3.0
  tflite_flutter: ^0.10.4   
  convert: ^3.1.1
  firebase_core: ^3.2.0
  cloud_functions: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/text_classification_model.tflite
    - lib/assets/tokenizer_config.json
