// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE6EXMK0DS34W0YsgmcPKldf-hectUYd4',
    appId: '1:183293762516:web:405af8882fcb5c9789d441',
    messagingSenderId: '183293762516',
    projectId: 'broke-uibranch',
    authDomain: 'broke-uibranch.firebaseapp.com',
    databaseURL: 'https://broke-uibranch-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'broke-uibranch.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPBow9AilNYF0WoRr_qUtHWFGIRdj_z7I',
    appId: '1:183293762516:android:aeeaf83f423f230989d441',
    messagingSenderId: '183293762516',
    projectId: 'broke-uibranch',
    databaseURL: 'https://broke-uibranch-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'broke-uibranch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIVgQQ8BYWbMTbHqMF0eZfUHZKdM2Lr7Y',
    appId: '1:183293762516:ios:633e921e46f85e1e89d441',
    messagingSenderId: '183293762516',
    projectId: 'broke-uibranch',
    databaseURL: 'https://broke-uibranch-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'broke-uibranch.appspot.com',
    androidClientId: '183293762516-v2bml942jcp44kh8946e4untb4dfm5kn.apps.googleusercontent.com',
    iosClientId: '183293762516-t7nid4k6cjo174kel72fe5c91sg6oc6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.brokeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIVgQQ8BYWbMTbHqMF0eZfUHZKdM2Lr7Y',
    appId: '1:183293762516:ios:633e921e46f85e1e89d441',
    messagingSenderId: '183293762516',
    projectId: 'broke-uibranch',
    databaseURL: 'https://broke-uibranch-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'broke-uibranch.appspot.com',
    iosBundleId: 'com.example.brokeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE6EXMK0DS34W0YsgmcPKldf-hectUYd4',
    appId: '1:183293762516:web:d8a6a51e6ae1ae5789d441',
    messagingSenderId: '183293762516',
    projectId: 'broke-uibranch',
    authDomain: 'broke-uibranch.firebaseapp.com',
    databaseURL: 'https://broke-uibranch-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'broke-uibranch.appspot.com',
  );
}